<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pets = [
            [
                'name' => 'Rocko',
                'image' => '1775691021_Captura de pantalla 2026-03-26 200619.png',
                'kind' => 'Dog',
                'weight' => 4,
                'age' => 6,
                'bread' => 'creole',
                'location' => 'villamaria caldas',
                'description' => 'He is a calm dog and is friendly to everyone.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-03-21 04:58:48',
                'updated_at' => '2026-04-09 04:30:21',
            ],
            [
                'name' => 'Michuelo',
                'image' => 'no-image.png',
                'kind' => 'gato',
                'weight' => 5.5,
                'age' => 18,
                'bread' => 'Esfinge',
                'location' => 'Columbia',
                'description' => 'El mas salvaje del planeta pero el mas feliz en la calle',
                'active' => 1,
                'adopted' => 1,
                'created_at' => '2026-03-21 04:58:48',
                'updated_at' => '2026-05-22 04:55:13',
            ],
            [
                'name' => 'Juan',
                'image' => 'no-image.png',
                'kind' => 'Horse',
                'weight' => 16,
                'age' => 2,
                'bread' => 'friesian',
                'location' => 'Llanitos villamaria Caldas',
                'description' => 'He is a beautiful and calm horse who loves to trot all over the countryside, happy with life.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-03-21 04:58:48',
                'updated_at' => '2026-03-21 04:58:48',
            ],
            [
                'name' => 'Roberto',
                'image' => 'no-image.png',
                'kind' => 'pig',
                'weight' => 5,
                'age' => 1,
                'bread' => 'mini pig',
                'location' => 'buenaventura Valle del cauca',
                'description' => 'Its a pig that eats people and loves pork.',
                'active' => 1,
                'adopted' => 1,
                'created_at' => '2026-03-21 04:58:48',
                'updated_at' => '2026-03-21 04:58:48',
            ],
            [
                'name' => 'chilindrina',
                'image' => 'no-image.png',
                'kind' => 'cow',
                'weight' => 15,
                'age' => 3,
                'bread' => 'angus',
                'location' => 'Bereira risaralda',
                'description' => 'Shes a quiet cow, bored of living in Bereira.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-03-21 04:58:48',
                'updated_at' => '2026-03-21 04:58:48',
            ],
            [
                'name' => 'Max',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 12.5,
                'age' => 3,
                'bread' => 'Labrador Retriever',
                'location' => 'Manizales Caldas',
                'description' => 'Juguetón y muy amigable con los niños.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Bella',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 8.2,
                'age' => 2,
                'bread' => 'Beagle',
                'location' => 'Pereira Risaralda',
                'description' => 'Muy activa y le encanta olfatear todo.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Rocky',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 15,
                'age' => 4,
                'bread' => 'Bulldog Francés',
                'location' => 'Armenia Quindío',
                'description' => 'Tranquilo y cariñoso, ideal para apartamento.',
                'active' => 1,
                'adopted' => 1,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Luna',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 18.3,
                'age' => 5,
                'bread' => 'Golden Retriever',
                'location' => 'Dosquebradas Risaralda',
                'description' => 'Muy obediente y buena con otros animales.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Toby',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 5.7,
                'age' => 1,
                'bread' => 'Poodle',
                'location' => 'Chinchiná Caldas',
                'description' => 'Pequeño, inteligente y aprende trucos rápido.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Coco',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 9.4,
                'age' => 2,
                'bread' => 'Shih Tzu',
                'location' => 'La Virginia Risaralda',
                'description' => 'Cariñoso y le encanta estar en el regazo.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Lola',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 22,
                'age' => 6,
                'bread' => 'Pastor Alemán',
                'location' => 'Santa Rosa de Cabal Risaralda',
                'description' => 'Protectora y leal, excelente guardiana.',
                'active' => 1,
                'adopted' => 1,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Simba',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 11.2,
                'age' => 3,
                'bread' => 'Husky Siberiano',
                'location' => 'Villamaría Caldas',
                'description' => 'Energético y le gusta el frío.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Milo',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 7.5,
                'age' => 2,
                'bread' => 'Corgi',
                'location' => 'Manizales Caldas',
                'description' => 'Muy alegre y siempre mueve la cola.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Nala',
                'image' => 'no-image.png',
                'kind' => 'Dog',
                'weight' => 14,
                'age' => 4,
                'bread' => 'Dálmata',
                'location' => 'Pereira Risaralda',
                'description' => 'Corredora nata, necesita espacio.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Mimi',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 3.2,
                'age' => 2,
                'bread' => 'Persa',
                'location' => 'Armenia Quindío',
                'description' => 'Tranquila y le gusta dormir mucho.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Garfield',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 5.1,
                'age' => 4,
                'bread' => 'Naranja atigrado',
                'location' => 'Manizales Caldas',
                'description' => 'Le encanta comer y dormir, muy sociable.',
                'active' => 1,
                'adopted' => 1,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Luna',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 2.8,
                'age' => 1,
                'bread' => 'Siamés',
                'location' => 'Pereira Risaralda',
                'description' => 'Muy curiosa y habladora.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Simón',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 4,
                'age' => 3,
                'bread' => 'Europeo común',
                'location' => 'Dosquebradas Risaralda',
                'description' => 'Cazador nato, muy independiente.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Cleo',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 3.5,
                'age' => 2,
                'bread' => 'Bengalí',
                'location' => 'Villamaría Caldas',
                'description' => 'Activa y le gusta el agua.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Bigotes',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 4.2,
                'age' => 5,
                'bread' => 'Maine Coon',
                'location' => 'Santa Rosa de Cabal Risaralda',
                'description' => 'Grande y manso, muy cariñoso.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Canela',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 2.9,
                'age' => 1,
                'bread' => 'Carey',
                'location' => 'Chinchiná Caldas',
                'description' => 'Juguetona y un poco traviesa.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Zeus',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 3.8,
                'age' => 3,
                'bread' => 'Ragdoll',
                'location' => 'La Virginia Risaralda',
                'description' => 'Se pone flácido cuando lo alzas, muy mimoso.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Misha',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 3,
                'age' => 2,
                'bread' => 'Azul ruso',
                'location' => 'Manizales Caldas',
                'description' => 'Callada y elegante.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Pelusa',
                'image' => 'no-image.png',
                'kind' => 'cat',
                'weight' => 3.3,
                'age' => 4,
                'bread' => 'Común europeo',
                'location' => 'Pereira Risaralda',
                'description' => 'Muy cariñosa y ronronea mucho.',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-21 23:21:30',
                'updated_at' => '2026-05-21 23:21:30',
            ],
            [
                'name' => 'Firulais',
                'image' => 'no-image.png',
                'kind' => 'Perro',
                'weight' => 25.5,
                'age' => 3,
                'bread' => 'Labrador',
                'location' => 'Bogotá',
                'description' => 'Perro muy amigable',
                'active' => 1,
                'adopted' => 0,
                'created_at' => '2026-05-22 04:46:12',
                'updated_at' => '2026-05-22 04:46:12',
            ],
        ];

        DB::table('pets')->insert($pets);
    }
}
